// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brkwutlijulbcrpgsjwd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJya3d1dGxpanVsYmNycGdzandkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5OTM0ODQsImV4cCI6MjA2MzU2OTQ4NH0.2p999PtKPFhM1v5OAoz8g8e0cmZfvnWNX9OsVB09M9Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);